# Generated by Django 5.1.6 on 2025-03-18 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_management', '0001_initial'),
        ('equipements_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgence', models.IntegerField(choices=[(0, 'Urgence vitale'), (1, 'Urgence élevée'), (2, 'Urgence modérée'), (3, 'Faible urgence')], default=3)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('description', models.TextField()),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_management.admin')),
                ('id_equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements_management.equipement')),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_management.personnel')),
                ('id_technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_management.technicien')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intervention_management.status')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions_effectuees', models.TextField(verbose_name='Actions Effectuées')),
                ('pieces_remplacees', models.TextField(blank=True, null=True, verbose_name='Pièces Remplacées')),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Maintenance Préventive'), ('corrective', 'Maintenance Corrective')], max_length=50)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='intervention_management.intervention')),
            ],
        ),
    ]
