# Generated by Django 5.1.6 on 2025-03-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='InterventionRecord',
        ),
    ]
