# Generated by Django 5.1.6 on 2025-03-13 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intervention_management.status'),
        ),
    ]
