# Generated by Django 5.1.6 on 2025-03-20 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0002_alter_user_numero_tel'),
        ('intervention_management', '0002_intervention_notes_delete_interventionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='id_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_management.personnel'),
        ),
    ]
