# Generated by Django 5.1.6 on 2025-03-13 23:37

from django.db import migrations

def create_default_statuses(apps, schema_editor):
    Status = apps.get_model('intervention_management', 'Status')
    default_statuses = [
        {'name': 'En attente', 'description': 'L\'intervention est en attente de traitement'},
        {'name': 'Affectée', 'description': 'L\'intervention a été affectée à un technicien'},
        {'name': 'En cours', 'description': 'L\'intervention est en cours de réalisation'},
        {'name': 'Terminée', 'description': 'L\'intervention a été réalisée et terminée'}
    ]
    for status in default_statuses:
        Status.objects.create(**status)

def remove_statuses(apps, schema_editor):
    Status = apps.get_model('intervention_management', 'Status')
    Status.objects.filter(name__in=['En attente', 'Affectée', 'En cours', 'Terminée']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('intervention_management', '0002_status_alter_intervention_statut'),
    ]

    operations = [
        migrations.RunPython(create_default_statuses, remove_statuses),
    ]
