# Generated by Django 5.1.6 on 2025-03-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_management', '0003_alter_intervention_id_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
