# Generated by Django 5.1.6 on 2025-04-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0003_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='Photo de profil'),
        ),
    ]
