# Generated by Django 5.1.6 on 2025-05-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_notif',
            field=models.BooleanField(default=True, verbose_name='Notifications actives'),
        ),
        migrations.AddField(
            model_name='user',
            name='active_notif_email',
            field=models.BooleanField(default=True, verbose_name='Notifications par email actives'),
        ),
    ]
