# Generated by Django 5.1.6 on 2025-04-17 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_management', '0001_initial'),
        ('equipements_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': "Statut d'intervention",
                'verbose_name_plural': "Statuts d'intervention",
            },
        ),
        migrations.CreateModel(
            name='InterventionPreventive',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('id_intervention', models.AutoField(primary_key=True,
                 serialize=False, verbose_name="ID d'intervention")),
                ('urgence', models.IntegerField(blank=True, choices=[(0, 'Urgence vitale'), (1, 'Urgence élevée'), (
                    2, 'Urgence modérée'), (3, 'Faible urgence')], default=3, null=True, verbose_name="Niveau d'urgence")),
                ('date_debut', models.DateTimeField(
                    blank=True, null=True, verbose_name='Date de début')),
                ('blocked', models.BooleanField(
                    default=False, verbose_name='Bloqué')),
                ('description', models.TextField(
                    blank=True, null=True, verbose_name='Description')),
                ('notes', models.TextField(
                    blank=True, null=True, verbose_name='Notes')),
                ('period', models.DurationField(blank=True, null=True,
                 verbose_name="Date d'intervention préventive")),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 to='accounts_management.admin', verbose_name='Administrateur')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='equipements_management.equipement', verbose_name='Équipement')),
                ('technicien', models.ManyToManyField(
                    blank=True, to='accounts_management.technicien', verbose_name='Technicien')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                 to='interventions_management.statusintervention', verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterventionCurrative',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('id_intervention', models.AutoField(primary_key=True,
                 serialize=False, verbose_name="ID d'intervention")),
                ('urgence', models.IntegerField(blank=True, choices=[(0, 'Urgence vitale'), (1, 'Urgence élevée'), (
                    2, 'Urgence modérée'), (3, 'Faible urgence')], default=3, null=True, verbose_name="Niveau d'urgence")),
                ('date_debut', models.DateTimeField(
                    blank=True, null=True, verbose_name='Date de début')),
                ('blocked', models.BooleanField(
                    default=False, verbose_name='Bloqué')),
                ('description', models.TextField(
                    blank=True, null=True, verbose_name='Description')),
                ('notes', models.TextField(
                    blank=True, null=True, verbose_name='Notes')),
                ('date_fin', models.DateTimeField(
                    blank=True, null=True, verbose_name='Date de fin')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 to='accounts_management.admin', verbose_name='Administrateur')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='equipements_management.equipement', verbose_name='Équipement')),
                ('technicien', models.ManyToManyField(
                    blank=True, to='accounts_management.technicien', verbose_name='Technicien')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 to='accounts_management.personnel', verbose_name='Utilisateur')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                 to='interventions_management.statusintervention', verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'abstract': False,
            },
        ),
    ]
