# Generated by Django 5.1.6 on 2025-04-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_management', '0001_initial'),
        ('equipements_management', '0002_alter_equipement_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('preventive', 'Intervention préventive'), ('currative', 'Intervention currative')], max_length=20, verbose_name="Type d'intervention")),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('urgence', models.IntegerField(blank=True, choices=[(0, 'Urgence vitale'), (1, 'Urgence élevée'), (2, 'Urgence modérée'), (3, 'Faible urgence')], default=3, null=True, verbose_name="Niveau d'urgence")),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('blocked', models.BooleanField(default=False, verbose_name='Bloqué')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_management.admin', verbose_name='Administrateur')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements_management.equipement', verbose_name='Équipement')),
                ('technicien', models.ManyToManyField(blank=True, to='accounts_management.technicien', verbose_name='Technicien')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
            },
        ),
        migrations.CreateModel(
            name='StatusIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': "Statut d'intervention",
                'verbose_name_plural': "Statuts d'intervention",
            },
        ),
        migrations.CreateModel(
            name='InterventionPreventive',
            fields=[
                ('intervention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interventions_management.intervention')),
                ('period', models.DurationField(blank=True, null=True, verbose_name="Période d'intervention préventive")),
            ],
            options={
                'verbose_name': 'Intervention préventive',
                'verbose_name_plural': 'Interventions préventives',
            },
            bases=('interventions_management.intervention',),
        ),
        migrations.AddField(
            model_name='intervention',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interventions_management.statusintervention', verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='InterventionCurrative',
            fields=[
                ('intervention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interventions_management.intervention')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_management.personnel', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Intervention currative',
                'verbose_name_plural': 'Interventions curratives',
            },
            bases=('interventions_management.intervention',),
        ),
    ]
