# Generated by Django 5.1.6 on 2025-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='blocked',
        ),
        migrations.AlterField(
            model_name='interventionpreventive',
            name='period',
            field=models.DurationField(blank=True, verbose_name="Période d'intervention préventive"),
        ),
    ]
