# Generated by Django 5.1.6 on 2025-02-23 11:22

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Administrateur', 'Administrateur'), ('Technicien', 'Technicien'), ('Personnel', 'Personnel')], default='Personnel', max_length=15, verbose_name='Rôle')),
                ('numero_tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('password', models.CharField(max_length=100, verbose_name='Mot de passe')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Photo de profil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equipement', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID Equipement')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('En service', 'En service'), ('En maintenance', 'En maintenance'), ('En panne', 'En panne')], default='En service', max_length=20)),
                ('manuel', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('disponibilite', models.BooleanField(default=True)),
                ('poste', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgence', models.IntegerField(choices=[(0, 'Urgence vitale'), (1, 'Urgence élevée'), (2, 'Urgence modérée'), (3, 'Faible urgence')], default=3)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Affectee', 'Affectée'), ('En cours', 'En cours'), ('Terminee', 'Terminée')], max_length=50)),
                ('description', models.TextField()),
                ('id_equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.equipement')),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.admin')),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.personnel')),
                ('id_technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.technicien')),
            ],
        ),
    ]
