# Generated by Django 5.1.6 on 2025-02-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
