# Generated by Django 5.1.6 on 2025-04-17 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': "Catégorie d'équipement",
                'verbose_name_plural': "Catégories d'équipements",
            },
        ),
        migrations.CreateModel(
            name='EtatEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': "État d'équipement",
                'verbose_name_plural': "États d'équipements",
            },
        ),
        migrations.CreateModel(
            name='LocalisationEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': "Localisation d'équipement",
                'verbose_name_plural': "Localisations d'équipements",
            },
        ),
        migrations.CreateModel(
            name='TypeEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='equipements_management.categorieequipement')),
            ],
            options={
                'verbose_name': "Type d'équipement",
                'verbose_name_plural': "Types d'équipements",
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equipement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('manuel', models.FileField(blank=True, null=True, upload_to='manuals/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipements_pics/', verbose_name='Photo équipement')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipements_management.categorieequipement')),
                ('etat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipements_management.etatequipement')),
                ('localisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipements_management.localisationequipement')),
                ('typee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipements_management.typeequipement')),
            ],
        ),
    ]
