# Generated by Django 5.1.6 on 2025-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements_management', '0002_alter_equipement_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='code',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Code inventaire'),
        ),
    ]
