# Generated by Django 5.1.6 on 2025-03-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equipement', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID Equipement')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('En service', 'En service'), ('En maintenance', 'En maintenance'), ('En panne', 'En panne')], default='En service', max_length=20)),
                ('manuel', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
