# Generated by Django 5.1.6 on 2025-03-18 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtatEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "État d'équipement",
                'verbose_name_plural': "États d'équipements",
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equipement', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID Equipement')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('manuel', models.BinaryField(blank=True, null=True)),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipements_management.etatequipement')),
            ],
        ),
    ]
