# Generated by Django 5.1.6 on 2025-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='id_equipement',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='localisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]