# Generated by Django 5.1.6 on 2025-04-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements_management.categorieequipement'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements_management.localisationequipement'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='typee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements_management.typeequipement'),
        ),
    ]
