# Generated by Django 5.1.6 on 2025-03-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements_management', '0002_alter_equipement_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='id_equipement',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]