# Generated by Django 5.1.6 on 2025-05-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements_management', '0003_equipement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photoéquipement'),
        ),
    ]
