# Generated by Django 5.1.6 on 2025-03-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements_management', '0004_alter_equipement_id_equipement'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='custom_localisation',
            field=models.CharField(blank=True, help_text='utilser ce champ si other est selectionné', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='localisation',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('AP1', 'AP1'), ('ME', 'ME'), ('M4', 'M4'), ('CP2', 'CP2'), ('CP6', 'CP6'), ('S4b', 'S4b'), ('S7', 'S7'), ('S11', 'S11'), ('S15', 'S15'), ('S19', 'S19'), ('DPGR1', 'DPGR1'), ('A2', 'A2'), ('AP2', 'AP2'), ('M1', 'M1'), ('M5', 'M5'), ('CP3', 'CP3'), ('CP7', 'CP7'), ('S4', 'S4'), ('S8', 'S8'), ('S12', 'S12'), ('S16', 'S16'), ('S20', 'S20'), ('DPGR2', 'DPGR2'), ('A3', 'A3'), ('CYB', 'CYB'), ('M2', 'M2'), ('MH', 'MH'), ('CP4', 'CP4'), ('CP8', 'CP8'), ('S5', 'S5'), ('S9', 'S9'), ('S13', 'S13'), ('S17', 'S17'), ('S21', 'S21'), ('MC1', 'MC1'), ('A4', 'A4'), ('SCBP', 'SCBP'), ('M3', 'M3'), ('CP1', 'CP1'), ('CP5', 'CP5'), ('CP9', 'CP9'), ('S6', 'S6'), ('S10', 'S10'), ('S14', 'S14'), ('S18', 'S18'), ('Visio', 'Visio'), ('MC2', 'MC2'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
    ]
