# Generated by Django 5.1.6 on 2025-03-20 07:23

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_tel',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Entrez le numéro au format international (ex: +213XXXXXXXXX)', max_length=128, null=True, region='DZ', unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
