# Generated by Django 5.1.6 on 2025-03-22 19:12

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management', '0002_alter_user_numero_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='poste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_tel',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Entrez le numéro au format international (ex: +213XXXXXXXXX)', max_length=128, null=True, region=None, unique=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mot de passe'),
        ),
    ]
