# Generated by Django 5.1.6 on 2025-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions_management', '0002_remove_intervention_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionpreventive',
            name='period',
            field=models.DurationField(blank=True, null=True, verbose_name="Période d'intervention préventive"),
        ),
    ]
