# Generated by Django 5.1.6 on 2025-05-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions_management', '0002_remove_intervention_blocked_and_more'),
        ('notifications_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_active',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interventions_management.intervention'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'Nouvelle Intervention AssignÃ©e'), ('reminder', "Rappel d'Intervention")], max_length=10),
        ),
    ]
